_base_: xattn_clean_coco_stuff.yml

method_name: Talk2DINO_XAttnBridge_Clean

evaluate:
  pamr: false
  component_cpa_enabled: false
  rvs_enabled: false
  cars_enabled: false
  rcc_enabled: false
  vpa_enabled: false
  vab_enabled: false
  opc_enabled: false
  cpa_router_enabled: false
  usrc_enabled: false
  template: sub_imagenet_template
  task:
    - coco_stuff
  coco_stuff: src/open_vocabulary_segmentation/segmentation/configs/_base_/datasets/stuff.py

postprocess:
  mode: none
