model:
  act: tanh # None, tanh, relu or sigmoid
  hidden_layer: True
  dino_embed_dim: 768
  alignment_strategy: all_pairs_lse
  region_temperature: 0.10

train:
  lr: 0.0001
  ltype: 'infonce'
  num_epochs: 100
  batch_size: 128
  save_best_model: False
